# Generated by Django 4.0.5 on 2022-08-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codserie', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=30)),
                ('plataforma', models.CharField(max_length=30)),
                ('fecha', models.DateField(default=2000)),
                ('episodio', models.IntegerField()),
                ('temporada', models.IntegerField()),
                ('terminada', models.BooleanField(blank=True, default=False, null=True)),
                ('sinopsis', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='series')),
            ],
        ),
    ]
