# Generated by Django 4.0.5 on 2022-08-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='imagen',
            field=models.ImageField(null=True, upload_to='series'),
        ),
    ]
